### ISSUE TITLE
NewHTTPStats: http: panic serving

### ISSUE THREAD

**Issue by plourdedominic** [mochi-co/mqtt#230]
Description:

When using NewHTTPStats hook like that:

```
stats := listeners.NewHTTPStats("stats", "0.0.0.0:8080", nil, nil)
serverErr = server.AddListener(stats)
```

I got the following runtime error:

```
2023/05/18 13:24:37 http: panic serving 10.244.2.253:46622: runtime error: invalid memory address or nil pointer dereference
goroutine 117 [running]:
net/http.(*conn).serve.func1()
 /usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x8b4440, 0xcda1b0})
 /usr/local/go/src/runtime/panic.go:890 +0x263
github.com/mochi-co/mqtt/v2/system.(*Info).Clone(0x0)
 /go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.6/system/system.go:40 +0x2e
github.com/mochi-co/mqtt/v2/listeners.(*HTTPStats).jsonHandler(0x10001004710a6?, {0xa22c20, 0xc0003795e0}, 0x7fb37cfa3ed8?)
 /go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.6/listeners/http_sysinfo.go:110 +0x45
net/http.HandlerFunc.ServeHTTP(0xc0002c0200?, {0xa22c20?, 0xc0003795e0?}, 0x40d268?)
 /usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xa22c20, 0xc0003795e0}, 0xc00025a000)
 /usr/local/go/src/net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc0004197d0?}, {0xa22c20, 0xc0003795e0}, 0xc00025a000)
 /usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000202630, {0xa22e48, 0xc0005d5740})
 /usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
 /usr/local/go/src/net/http/server.go:3089 +0x5ed
 ```

I'm running my GO application inside a Docker like this (development):

```
FROM golang:1.20.3-bullseye as dev

RUN apt update && apt upgrade -y && \
    apt install -y git \
    make openssh-client

# Install the air binary so we get live code-reloading when we save files
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

# Run the air command in the directory where our code will live
WORKDIR /app/
CMD air
```

In production (I get the same error):

```
## Build
FROM golang:1.20.3-alpine3.17 AS build

WORKDIR /app/

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY *.go ./
COPY .env.example ./.env

RUN go build -o /mqtt-broker



## Deploy
FROM gcr.io/distroless/base-debian11 as prod

WORKDIR /

COPY --from=build /mqtt-broker /mqtt-broker
COPY --from=build /app/.env /.env

EXPOSE 1883 8883 8080

USER nonroot:nonroot

ENTRYPOINT ["/mqtt-broker"]
```

what did I do wrong?
Thanks
Dominic

**Comment by mochi-co** [comment]
Currently `NewHTTPStats` requires a point to the server info in order to access the server data.
```go
server := mqtt.New(nil)
_ = server.AddHook(new(auth.AllowHook), nil)
stats := listeners.NewHTTPStats("stats", *infoAddr, nil, server.Info)
```

I'm hoping to convert this to a hook in the future (which will also allow prometheus as a hook), but haven't gotten to it yet.

**Comment by plourdedominic** [comment]
Thanks a lot for the quick reply.

I created a PR to update the example: https://github.com/mochi-co/mqtt/pull/231
